<a href="https://colab.research.google.com/github/ananyatrivedi1/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


## Introduction to Tensors

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor([7])
scalar

tensor([7])

In [ ]:
scalar.ndim

1

In [ ]:
vector = torch.tensor([[[7, 7, 7],
                        [7, 7, 7]],
                       [[7, 7, 7],
                        [7, 7, 7]]])
print(vector.ndim)
print(vector.shape)

3
torch.Size([2, 2, 3])


In [ ]:
vector.shape

torch.Size([2, 2, 3])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[7,8, 9],
                       [9,10, 11],
                       [11, 12, 13]])
TENSOR.shape

torch.Size([3, 3])

### Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0035, 0.6739, 0.4928, 0.1652],
        [0.0094, 0.7037, 0.9957, 0.7805],
        [0.4112, 0.2587, 0.3399, 0.4218]])

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(5, 5, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([5, 5, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[9.2174e-01, 5.2033e-01, 9.5202e-01],
         [8.2603e-01, 5.4645e-01, 9.6817e-01],
         [1.1708e-01, 9.1503e-01, 9.6956e-01],
         [6.4280e-01, 6.9538e-01, 4.8996e-01],
         [3.9088e-01, 1.8894e-01, 7.9620e-02]],

        [[4.4493e-01, 5.1802e-02, 6.2589e-01],
         [2.8993e-01, 9.9226e-01, 9.0430e-01],
         [5.2233e-01, 7.4687e-01, 3.7945e-01],
         [4.7291e-01, 2.0861e-01, 1.1042e-01],
         [9.5574e-01, 8.4930e-01, 8.6502e-01]],

        [[1.6321e-01, 6.4088e-01, 6.5348e-01],
         [6.0604e-01, 4.9917e-02, 7.1056e-01],
         [7.2000e-01, 2.3014e-01, 5.2408e-01],
         [4.9899e-02, 8.6474e-04, 3.1191e-01],
         [8.7089e-01, 5.9834e-01, 4.1438e-01]],

        [[4.8043e-02, 4.8351e-01, 3.0033e-01],
         [6.9092e-01, 3.0092e-01, 2.3309e-01],
         [3.4248e-01, 7.5142e-02, 2.9009e-01],
         [2.1473e-01, 6.7184e-01, 6.0111e-01],
         [7.3223e-01, 6.2147e-01, 8.6644e-01]],

        [[4.5078e-01, 4.2967e-01, 7.2440e-01],
     

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=0.5)
zero_to_ten

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [ ]:
some_tensor = torch.rand(2, 3, 4)

# details
print(some_tensor)
print(some_tensor.ndim)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[[0.0771, 0.9369, 0.2114, 0.6406],
         [0.7178, 0.9259, 0.3001, 0.7661],
         [0.6379, 0.8386, 0.5901, 0.9200]],

        [[0.0323, 0.1337, 0.1197, 0.4230],
         [0.4471, 0.2003, 0.1592, 0.1246],
         [0.8158, 0.8686, 0.2612, 0.8450]]])
3
Shape of tensor: torch.Size([2, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 237 µs, sys: 871 µs, total: 1.11 ms
Wall time: 1.53 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 241 µs, sys: 0 ns, total: 241 µs
Wall time: 188 µs


tensor(14)

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
import torch

In [ ]:
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(8, 1)
x_reshaped, x_reshaped.shape

(tensor([[0.],
         [2.],
         [3.],
         [4.],
         [0.],
         [6.],
         [7.],
         [8.]]),
 torch.Size([8, 1]))

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(2, 4)
z, z.shape, x

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
# Replaces all values of the 0th dimension & the 0 index if the 1st dimension
z[:, 0] = 0
z, x

(tensor([[0., 2., 3., 4.],
         [0., 6., 7., 8.]]),
 tensor([0., 2., 3., 4., 0., 6., 7., 8.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[0., 0., 0., 0.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [0., 0., 0., 0.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[0.],
        [2.],
        [3.],
        [4.],
        [0.],
        [6.],
        [7.],
        [8.]])
Previous shape: torch.Size([8, 1])

New tensor: tensor([0., 2., 3., 4., 0., 6., 7., 8.])
New shape: torch.Size([8])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([0., 2., 3., 4., 0., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[0.],
        [2.],
        [3.],
        [4.],
        [0.],
        [6.],
        [7.],
        [8.]])
New shape: torch.Size([8, 1])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (Selecting Data from Tensors)


In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][1]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([4, 5, 6])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

##Tensors and NumPy

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.4013, 0.0412, 0.5089, 0.1786],
        [0.6937, 0.5969, 0.4921, 0.2384],
        [0.3672, 0.9950, 0.7495, 0.0480]])

Tensor B:
tensor([[0.4719, 0.8797, 0.2623, 0.4167],
        [0.5836, 0.8318, 0.8050, 0.4941],
        [0.2806, 0.1968, 0.0025, 0.7610]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Set the random seed
RANDOM_SEED=4
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.5596, 0.5591, 0.0915, 0.2100],
        [0.0072, 0.0390, 0.9929, 0.9131],
        [0.6186, 0.9744, 0.3189, 0.2148]])

Tensor D:
tensor([[0.5596, 0.5591, 0.0915, 0.2100],
        [0.0072, 0.0390, 0.9929, 0.9131],
        [0.6186, 0.9744, 0.3189, 0.2148]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## GPU

In [ ]:
import torch as t
device = "cuda" if t.cuda.is_available() else "cpu"

In [ ]:
tensor = t.tensor([1,2,3])
# tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu #numpy only works on cpu
# tensor_back_on_cpu = tensor_on_gpu.cpu().numpy

tensor([1, 2, 3])